// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duzqcvwtvffapbxjzodv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1enFjdnd0dmZmYXBieGp6b2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Njg1ODEsImV4cCI6MjA2NjM0NDU4MX0.ojFQwWOWjhWCeQNSvdMTyxNDpLbwWe4k3dUEloFglvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);